name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout g-core
      uses: actions/checkout@v3
      
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Checkout g-api
      uses: actions/checkout@v4
      with:
        repository: umu-art/g-api
      
    - name: Build g-api
      run: chmod 777 ./build-server-api.sh && /bin/bash ./build-server-api.sh

    - name: Checkout g-core
      uses: actions/checkout@v3
    
    - name: Build and test g-core
      run: mvn -B package --file pom.xml
      
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6


  sync-server:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: echo hi
      
    
